2021-02-28T07:40:39-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:42:17-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:43:06-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:43:36-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:44:06-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:45:19-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(224): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:48:53-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:50:58-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:53:41-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:54:11-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(226): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:55:53-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "viaje_id" of relation "viaje" does not exist
LINE 1: INSERT INTO "viaje" ("fecha", "hora", "bus", "viaje_id", "de...
                                                     ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#6 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "viaje_id" of relation "viaje" does not exist
LINE 1: INSERT INTO "viaje" ("fecha", "hora", "bus", "viaje_id", "de...
                                                     ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#5 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}
2021-02-28T07:56:44-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  time zone "hos-387" not recognized' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#6 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  time zone "hos-387" not recognized' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#5 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}
2021-02-28T07:59:25-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "carril" violates not-null constraint' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#6 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "carril" violates not-null constraint' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "vi...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "vi...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('viaje', Array)
#5 /var/www/test/Encomiendas/application/models/Viaje.php(225): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}
2021-02-28T08:15:45-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[P0001]: Raise exception: 7 ERROR:  No puede crear 2 manifiestos en un mismo viaje un mismo encargado.' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "ma...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "ma...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('manifiesto', Array)
#6 /var/www/test/Encomiendas/application/models/Viaje.php(247): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[P0001]: Raise exception: 7 ERROR:  No puede crear 2 manifiestos en un mismo viaje un mismo encargado.' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "ma...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "ma...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('manifiesto', Array)
#5 /var/www/test/Encomiendas/application/models/Viaje.php(247): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}
2021-02-28T08:17:02-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[P0001]: Raise exception: 7 ERROR:  No puede crear 2 manifiestos en un mismo viaje un mismo encargado.' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "ma...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "ma...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('manifiesto', Array)
#6 /var/www/test/Encomiendas/application/models/Viaje.php(247): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[P0001]: Raise exception: 7 ERROR:  No puede crear 2 manifiestos en un mismo viaje un mismo encargado.' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO "ma...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO "ma...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1056): Zend_Db_Adapter_Abstract->insert('manifiesto', Array)
#5 /var/www/test/Encomiendas/application/models/Viaje.php(247): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}
2021-02-28T11:58:12-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#5 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#5 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#6 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#7 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#12 {main}
2021-02-28T11:59:44-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#5 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#5 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#6 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#7 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#12 {main}
2021-02-28T12:01:05-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#5 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#6 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#7 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#8 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#13 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000001" requires 1' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /var/www/test/Encomiendas/application/models/ChoferViaje.php(26): Zend_Db_Adapter_Abstract->fetchAssoc(Object(Zend_Db_Select))
#5 /var/www/test/Encomiendas/application/controllers/EnvioController.php(84): App_Model_ChoferViaje->getChoferesViaje(NULL)
#6 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->editChoferesViajeAction()
#7 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('editChoferesVia...')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#12 {main}
