2021-02-28T06:53:32-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T06:53:32-04:00 ERR (3): exception 'Zend_Db_Exception' with message 'No se pudo registrar el Viaje ' in /var/www/test/Encomiendas/application/models/Viaje.php:269
Stack trace:
#0 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#1 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#2 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#3 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#5 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#6 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#7 {main}
2021-02-28T07:25:33-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
2021-02-28T07:25:33-04:00 ERR (3): exception 'Zend_Db_Exception' with message 'No se pudo registrar el Viaje ' in /var/www/test/Encomiendas/application/models/Viaje.php:270
Stack trace:
#0 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#1 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#2 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#3 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#5 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#6 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#7 {main}
2021-02-28T07:28:58-04:00 ERR (3): exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#5 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#6 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#7 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#8 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#9 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#10 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#11 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#15 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "viaje_id_viaje_seq" does not exist
LINE 1: SELECT NEXTVAL('"viaje_id_viaje_seq"')
                       ^' in /var/www/test/Encomiendas/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /var/www/test/Encomiendas/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#2 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT NEXTVAL(...', Array)
#3 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT NEXTVAL(...', Array)
#4 /var/www/test/Encomiendas/library/Zend/Db/Adapter/Pdo/Pgsql.php(299): Zend_Db_Adapter_Abstract->fetchOne('SELECT NEXTVAL(...')
#5 /var/www/test/Encomiendas/library/Zend/Db/Table/Abstract.php(1041): Zend_Db_Adapter_Pdo_Pgsql->nextSequenceId('"viaje_id_viaje...')
#6 /var/www/test/Encomiendas/application/models/Viaje.php(222): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/test/Encomiendas/application/controllers/EnvioController.php(74): App_Model_Viaje->insertTX(Array, 'ciu-100', 'ciu-103')
#8 /var/www/test/Encomiendas/library/Zend/Controller/Action.php(513): EnvioController->addViajeAction()
#9 /var/www/test/Encomiendas/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('addViajeAction')
#10 /var/www/test/Encomiendas/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/test/Encomiendas/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/test/Encomiendas/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/test/Encomiendas/public/index.php(26): Zend_Application->run()
#14 {main}
